/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useEffect, useState, useRef, use } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { 
  AlertOctagon, 
  Terminal as TerminalIcon, 
  Activity, 
  Send, 
  Users, 
  DollarSign, 
  User, 
  Clock, 
  CheckCircle, 
  Megaphone, 
  Network as NetworkIcon,
  BookOpen,
  X
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { Nav } from "@/components/layout/nav";
import { incidentCatalog } from "@/lib/incident-catalog";

const domainStudyGuides: Record<string, {
  title: string;
  hindiExplanation: string;
  englishExplanation: string;
  checklist: string[];
  pitfalls: string;
}> = {
  WINDOWS: {
    title: "Windows Server & Active Directory Operations",
    hindiExplanation: "Active Directory (AD) pure office network ke logins aur permissions ko manage karta hai. Agar domain controller down ho jaye toh users sign in nahi kar paenge. DNS fail hone par hostnames kaam nahi karte, par public IP direct ping ho sakta hai. DHCP scope full hone par users ko local network IP milna band ho jata hai.",
    englishExplanation: "Active Directory acts as the centralized identity provider. OUTAGES: A DNS failure interrupts the domain lookup paths, which halts domain sign-ins. DHCP scope exhaustion prevents devices from allocating local IPs, resulting in APIPA addresses (169.254.x.x).",
    checklist: [
      "Check service states using command: 'sc query dns' or 'sc query dhcp'",
      "Verify connection parameters: check IP ping vs hostname lookup (nslookup)",
      "Audit AD sync status: run 'repadmin /showrepl' to check replica replication",
      "Check local storage disk usage parameters: 'df -h' or host datastore files"
    ],
    pitfalls: "Static DNS changes roll out karne se pehle primary zones ka configuration backup verify karein. Active Directory sync details skip mat karein."
  },
  NETWORK: {
    title: "Core Routing, VLAN Trunks & Firewall Zones",
    hindiExplanation: "Subnets ya network loop hone par broadcast traffic router CPU load ko 100% kar deta hai. Scheduled work ke baad connectivity chali jaye, toh verify karein ki Switch Uplink Trunk ports par target VLAN configuration me missing toh nahi ho gayi.",
    englishExplanation: "Broadcast storms generated by cabling loops block routing paths and trigger high router CPU utilization. Updating switch link settings can inadvertently prune required VLAN IDs from trunk lines, isolating subnets.",
    checklist: [
      "Verify switch dynamic paths: check 'show interface trunk' allowed lists",
      "Look for network loops indicators: audit 'show spanning-tree' status warnings",
      "Identify rule drops on firewalls: check logs via Nginx or security policies"
    ],
    pitfalls: "Access mode ports par Spanning Tree settings override na karein. Firewall rules me catch-all deny rule order ko top position par mat rakhein."
  },
  CLOUD: {
    title: "AWS Cloud, Dynamic IAM Roles & Storage IOPS",
    hindiExplanation: "Browser security policies CORS (Cross-Origin Resource Sharing) block karti hain agar S3 media buckets config me active domains block ho. Database transactions hang hona aksar gp2 EBS storage pools ke dynamic IOPS exhaustion ki wajah se hota hai.",
    englishExplanation: "CORS blocks outbound browser resource fetches if the host domain is omitted from S3 headers. Stalled database writes are usually caused by volume IOPS credits depletion during indexing operations.",
    checklist: [
      "Verify CORS rules settings on S3: run 'aws s3api get-bucket-cors'",
      "Audit active instance credentials role: check 'aws sts get-caller-identity'",
      "Review DB IO workload speed parameters: run 'iostat' or describe volume metrics"
    ],
    pitfalls: "AWS Access keys ko code ya static environment variables me hardcode na karein. Dynamic IAM role attachments ko always verify karein."
  },
  DEVOPS: {
    title: "CI/CD Pipelines, K8s Pods & Docker Discovery",
    hindiExplanation: "CrashLoopBackOff tab hota hai jab pod clean start toh hota hai par config secrets (jaise JWT_SECRET) missing ya error state me hone se crash ho jata hai. Runner host drive full hone se container images build and push block hote hain.",
    englishExplanation: "CrashLoopBackOff indicates container startup failures, commonly caused by missing Vault secrets or bad database hosts. Failed build runners are usually caused by uncleaned Docker build layer cache.",
    checklist: [
      "Review container status: run 'kubectl get pods' or get details via describe pod",
      "Read direct crash logs: check 'kubectl logs' output on failing containers",
      "Inspect runner drive capacity: execute 'df -h' and check docker volume df"
    ],
    pitfalls: "Liveness and Readiness probes verify kiye bina deploy configurations change na karein. Base image definitions clear rakhein."
  },
  SECURITY: {
    title: "Ransomware Containment, DDoS & Keys Leaks",
    hindiExplanation: "Ransomware files corrupt aur lock karta hai. Scope limit karne ke liye sabse pehle source host connection port shutdown/isolate karein. DDoS packets overload buffer zones ko fill karte hain, Cloudflare 'Under Attack' mode iska immediate protection solution hai.",
    englishExplanation: "Ransomware spreads through shared network folders. The first action must be host port isolation to block encryption streams. DDoS floods load balancer queues, requiring CDN JavaScript challenges to block botnets.",
    checklist: [
      "Track active SMB connections on NAS: check 'netstat -ano' for ports output",
      "Isolate infected source switch port directly to stop file renaming",
      "Check server version compatibility updates: check exchange patches history"
    ],
    pitfalls: "Attackers ko ransom payment na karein. Public Git repositories me commit push karne se pehle config scanning checks always enable rakhein."
  }
};

interface TimelineEvent {
  time: string;
  description: string;
  type: "ALERT" | "DIAGNOSTIC" | "COMMUNICATION" | "REMEDIATION" | "EVALUATION";
}

interface ChatMessage {
  sender: string;
  role: string;
  text: string;
  timestamp: string;
}

interface CommandRun {
  command: string;
  output: string;
  timestamp: string;
}

interface SessionData {
  id: string;
  role: string;
  title: string;
  domain: string;
  symptoms: string;
  status: string;
  timeElapsed: number;
  financialLoss: number;
  activeCommanderRole: string;
  alerts: any[];
  logs: string[];
  timeline: TimelineEvent[];
  chatHistory: ChatMessage[];
  commandsRun: CommandRun[];
  communicationLogs: any[];
}

export default function ActiveWarRoomPage({ params }: { params: Promise<{ sessionId: string }> }) {
  const router = useRouter();
  const { sessionId } = use(params);
  const [session, setSession] = useState<SessionData | null>(null);
  const [loading, setLoading] = useState(true);
  const [showStudyModal, setShowStudyModal] = useState(false);
  
  // Tabs & inputs state
  const [activeTab, setActiveTab] = useState<"terminal" | "telemetry" | "diagram">("terminal");
  const [activeCommander, setActiveCommander] = useState<string>("CTO");
  const [commandInput, setCommandInput] = useState("");
  const [chatInput, setChatInput] = useState("");
  
  // Status communication states
  const [commsTarget, setCommsTarget] = useState<string>("CTO");
  const [commsText, setCommsText] = useState("");
  const [commsStatusMessage, setCommsStatusMessage] = useState("");

  // Resolution console states
  const [rootCauseDiagnosis, setRootCauseDiagnosis] = useState("");
  const [selectedRemediationId, setSelectedRemediationId] = useState("");
  const [selectedPreventions, setSelectedPreventions] = useState<string[]>([]);
  const [submittingEvaluation, setSubmittingEvaluation] = useState(false);

  // Refs for auto-scrolling
  const terminalEndRef = useRef<HTMLDivElement>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Load session from API
  const fetchSession = async () => {
    try {
      const res = await fetch(`/api/troubleshooting/session/${sessionId}`);
      if (!res.ok) throw new Error("Failed to load session");
      const data = await res.json();
      setSession(data);
      if (data.status !== "INVESTIGATING") {
        // If already resolved, take to summary
        router.push(`/troubleshooting?sessionSummaryId=${sessionId}`);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSession();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId]);

  // Periodic timer tick (every 5 seconds) to update elapsed time and financial loss
  useEffect(() => {
    if (!session || session.status !== "INVESTIGATING") return;

    const timer = setInterval(async () => {
      try {
        const res = await fetch(`/api/troubleshooting/session/${sessionId}`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ action: "tick", seconds: 5 }),
        });
        if (res.ok) {
          const updated = await res.json();
          setSession((prev) => prev ? { 
            ...prev, 
            timeElapsed: updated.timeElapsed, 
            financialLoss: updated.financialLoss 
          } : null);
        }
      } catch (err) {
        console.error("Tick error:", err);
      }
    }, 5000);

    return () => clearInterval(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [session?.status, sessionId]);

  // Auto scroll terminal and chat
  useEffect(() => {
    terminalEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [session?.commandsRun]);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [session?.chatHistory, activeCommander]);

  if (loading) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center">
        <div className="h-12 w-12 animate-spin rounded-full border-4 border-[#00E5FF] border-t-transparent"></div>
        <p className="mt-4 text-zinc-400 font-mono">Connecting to GuruAI War Room server...</p>
      </div>
    );
  }

  if (!session) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center text-center">
        <AlertOctagon className="text-red-500" size={64} />
        <h2 className="mt-4 text-2xl font-bold text-white">Outage Session Not Found</h2>
        <Link href="/troubleshooting" className="mt-6 rounded-md bg-[#00E5FF] px-4 py-2 font-semibold text-[#050816]">
          Back to Incident Queue
        </Link>
      </div>
    );
  }

  // Find incident catalog template for additional specs
  const catalogTemplate = incidentCatalog.find((i) => i.title === session.title);

  // Send diagnostic command
  const handleRunCommand = async (e?: React.FormEvent, presetCmd?: string) => {
    if (e) e.preventDefault();
    const cmd = presetCmd || commandInput;
    if (!cmd.trim()) return;

    try {
      const res = await fetch(`/api/troubleshooting/session/${sessionId}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "run_command", command: cmd }),
      });
      if (res.ok) {
        const updated = await res.json();
        setSession(updated);
        setCommandInput("");
      }
    } catch (err) {
      console.error(err);
    }
  };

  // Send message to AI Commander
  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim()) return;

    const currentInput = chatInput;
    setChatInput(""); // Clear immediately for UX

    try {
      const res = await fetch(`/api/troubleshooting/session/${sessionId}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          action: "send_message", 
          text: currentInput, 
          commanderRole: activeCommander 
        }),
      });
      if (res.ok) {
        const updated = await res.json();
        setSession(updated);
      }
    } catch (err) {
      console.error(err);
    }
  };

  // Broadcast status update
  const handleSendStatusUpdate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!commsText.trim()) return;

    try {
      const res = await fetch(`/api/troubleshooting/session/${sessionId}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          action: "send_status_update", 
          text: commsText, 
          target: commsTarget 
        }),
      });
      if (res.ok) {
        const updated = await res.json();
        setSession(updated);
        setCommsText("");
        setCommsStatusMessage(`Status broadcast sent successfully to ${commsTarget}!`);
        setTimeout(() => setCommsStatusMessage(""), 3000);
      }
    } catch (err) {
      console.error(err);
    }
  };

  // Toggle checklist preventions
  const handleTogglePrevention = (p: string) => {
    setSelectedPreventions((prev) => 
      prev.includes(p) ? prev.filter((item) => item !== p) : [...prev, p]
    );
  };

  // Submit incident resolution for final grading
  const handleSubmitEvaluation = async () => {
    if (!rootCauseDiagnosis.trim()) {
      alert("Please provide your diagnosed root cause analysis note before resolving.");
      return;
    }
    if (!selectedRemediationId) {
      alert("Please select a remediation action to apply.");
      return;
    }

    setSubmittingEvaluation(true);
    try {
      const res = await fetch(`/api/troubleshooting/evaluate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sessionId,
          rootCauseDiagnosis,
          remediationId: selectedRemediationId,
          preventionSuggestions: selectedPreventions,
        }),
      });
      if (res.ok) {
        // Redirect to summary view of the session
        router.push(`/troubleshooting?sessionSummaryId=${sessionId}`);
      } else {
        const err = await res.json();
        alert(`Evaluation failed: ${err.error}`);
      }
    } catch (err) {
      console.error(err);
      alert("An error occurred during evaluation.");
    } finally {
      setSubmittingEvaluation(false);
    }
  };

  // Helper format time
  const formatTime = (totalSeconds: number) => {
    const mins = Math.floor(totalSeconds / 60);
    const secs = totalSeconds % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

  // Extract alerts or fall back
  const alerts = session.alerts || [];
  const chatHistory = session.chatHistory || [];
  const commandsRun = session.commandsRun || [];

  // Filter chats by active commander role
  const activeChats = chatHistory.filter(
    (m) => m.role === activeCommander || (m.sender === "Student" && m.timestamp) // simple filter to show matching role convo
  );

  return (
    <div className="min-h-screen">
      <Nav />

      {/* EMERGENCY URGENCY HEADER */}
      <div className="mb-6 rounded-2xl border border-red-500/30 bg-red-950/20 p-4 shadow-[0_0_30px_rgba(239,68,68,0.1)] backdrop-blur">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <span className="relative flex h-3 w-3">
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-red-400 opacity-75"></span>
              <span className="relative inline-flex h-3 w-3 rounded-full bg-red-500"></span>
            </span>
            <div>
              <p className="text-xs font-mono font-semibold tracking-wider text-red-400 uppercase">
                ACTIVE INCIDENT OUTAGE · SEV-1 CRITICAL
              </p>
              <h1 className="text-xl font-bold text-white md:text-2xl mt-0.5">
                {session.title}
              </h1>
            </div>
          </div>
          
          <div className="flex items-center gap-6">
            <button
              onClick={() => setShowStudyModal(true)}
              className="rounded-lg bg-gradient-to-r from-blue-500/20 to-purple-500/20 px-3 py-2 border border-blue-500/30 text-center hover:from-blue-500/30 hover:to-purple-500/30 transition cursor-pointer text-xs font-mono font-semibold text-[#00E5FF] flex items-center justify-center gap-1.5 shadow-[0_0_15px_rgba(0,229,255,0.05)]"
            >
              <BookOpen size={13} className="text-[#00FFB3]" /> Study Guide
            </button>

            <div className="rounded-lg bg-white/5 px-4 py-2 border border-white/10 text-center min-w-[100px]">
              <p className="text-[10px] font-mono text-zinc-400 uppercase tracking-widest flex items-center justify-center gap-1">
                <Clock size={10} /> Time Elapsed
              </p>
              <p className="text-lg font-bold font-mono text-[#00E5FF] mt-0.5">
                {formatTime(session.timeElapsed)}
              </p>
            </div>
            
            <div className="rounded-lg bg-red-500/10 px-4 py-2 border border-red-500/20 text-center min-w-[120px]">
              <p className="text-[10px] font-mono text-red-400 uppercase tracking-widest flex items-center justify-center gap-1">
                <DollarSign size={10} /> Business Cost
              </p>
              <p className="text-lg font-bold font-mono text-red-500 mt-0.5 animate-pulse">
                ${session.financialLoss.toLocaleString()}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* CORE 3-COLUMN WORKSPACE GRID */}
      <section className="grid gap-6 lg:grid-cols-[0.9fr_1.3fr_0.9fr] items-start mb-6">
        
        {/* LEFT COLUMN: BUSINESS IMPACT & PAGERDUTY ALERTS */}
        <div className="space-y-6">
          {/* Business Impact Card */}
          <Card className="p-5 border-white/10 bg-black/40">
            <h2 className="text-sm font-semibold tracking-wider text-zinc-400 uppercase mb-4 flex items-center gap-2">
              <Users size={16} className="text-[#00E5FF]" /> Business Impact
            </h2>
            <div className="space-y-4">
              <div>
                <p className="text-xs text-zinc-500">Service SLA Severity</p>
                <span className="mt-1 inline-block rounded bg-red-500/10 px-2 py-0.5 text-xs font-semibold text-red-400 border border-red-500/20">
                  {catalogTemplate?.severity || "P1"} Critical
                </span>
              </div>
              <div>
                <p className="text-xs text-zinc-500">Estimated Burn Rate</p>
                <p className="text-sm font-medium text-white mt-0.5">
                  ${catalogTemplate?.businessImpact.financialLossPerMinute || 500} USD / minute
                </p>
              </div>
              <div>
                <p className="text-xs text-zinc-500">Impacted Customers</p>
                <p className="text-sm font-medium text-white mt-0.5">
                  ~{catalogTemplate?.businessImpact.affectedUsers || 100} active sessions failing
                </p>
              </div>
              <div className="rounded-lg bg-white/[0.02] border border-white/5 p-3 text-xs text-zinc-400">
                <p className="font-semibold text-zinc-300 mb-1">Impact Summary:</p>
                {catalogTemplate?.businessImpact.description || "Outage affects authentication/gateway subsystems."}
              </div>
            </div>
          </Card>

          {/* Alerts Feed (PagerDuty Style) */}
          <Card className="p-5 border-white/10 bg-black/40">
            <h2 className="text-sm font-semibold tracking-wider text-zinc-400 uppercase mb-4 flex items-center gap-2">
              <AlertOctagon size={16} className="text-red-500" /> Live Alerts Feed
            </h2>
            <div className="space-y-2 max-h-[220px] overflow-y-auto pr-1">
              {alerts.map((alert: any) => (
                <div 
                  key={alert.id} 
                  className={`rounded-lg border p-3 text-xs flex gap-2 items-start transition ${
                    alert.severity === "CRITICAL" 
                      ? "border-red-500/20 bg-red-500/5 text-red-300" 
                      : "border-amber-500/20 bg-amber-500/5 text-amber-300"
                  }`}
                >
                  <span className="mt-0.5 flex h-2 w-2 shrink-0 rounded-full bg-current animate-pulse"></span>
                  <div className="space-y-0.5">
                    <p className="font-semibold">{alert.service}</p>
                    <p className="text-[11px] text-zinc-400 leading-normal">{alert.message}</p>
                    <span className="text-[10px] text-zinc-500 block mt-1">{alert.timestamp}</span>
                  </div>
                </div>
              ))}
            </div>
          </Card>

          {/* User Complaints */}
          <Card className="p-5 border-white/10 bg-black/40">
            <h2 className="text-sm font-semibold tracking-wider text-zinc-400 uppercase mb-4 flex items-center gap-2">
              <Megaphone size={16} className="text-amber-500" /> User Complaints Stream
            </h2>
            <div className="space-y-2 max-h-[160px] overflow-y-auto pr-1">
              {catalogTemplate?.userComplaints.map((comp, idx) => (
                <div key={idx} className="rounded-lg bg-white/[0.02] border border-white/5 p-3 text-xs leading-normal">
                  <p className="font-mono text-[10px] text-zinc-500 mb-1">User #{1032 + idx} · Ticket</p>
                  <p className="text-zinc-300">&quot;{comp}&quot;</p>
                </div>
              )) || (
                <p className="text-xs text-zinc-500 italic">No incoming user tickets reported yet.</p>
              )}
            </div>
          </Card>
        </div>

        {/* CENTER COLUMN: MAIN TRIAGE CONSOLE (TERMINAL / TELEMETRY / DIAGRAM) */}
        <div className="space-y-4">
          {/* Triage Mode Toggles */}
          <div className="flex border-b border-white/10 bg-black/20 rounded-t-xl overflow-hidden p-1 gap-1">
            <button 
              onClick={() => setActiveTab("terminal")}
              className={`flex-1 flex items-center justify-center gap-2 py-2.5 text-xs font-mono rounded-lg transition ${
                activeTab === "terminal" ? "bg-white/10 text-white shadow-inner" : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              <TerminalIcon size={14} /> Diagnostic Terminal
            </button>
            <button 
              onClick={() => setActiveTab("telemetry")}
              className={`flex-1 flex items-center justify-center gap-2 py-2.5 text-xs font-mono rounded-lg transition ${
                activeTab === "telemetry" ? "bg-white/10 text-white shadow-inner" : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              <Activity size={14} /> Live Telemetry
            </button>
            <button 
              onClick={() => setActiveTab("diagram")}
              className={`flex-1 flex items-center justify-center gap-2 py-2.5 text-xs font-mono rounded-lg transition ${
                activeTab === "diagram" ? "bg-white/10 text-white shadow-inner" : "text-zinc-400 hover:text-zinc-200"
              }`}
            >
              <NetworkIcon size={14} /> System Nodes
            </button>
          </div>

          {/* TAB 1: INTERACTIVE MONOSPACE TERMINAL */}
          {activeTab === "terminal" && (
            <Card className="border-white/10 bg-zinc-950 p-0 rounded-b-xl overflow-hidden shadow-2xl flex flex-col min-h-[480px]">
              <div className="border-b border-white/5 bg-zinc-900 px-4 py-2 flex items-center justify-between">
                <span className="font-mono text-xs text-zinc-500">triage-runner@guruai-node-01</span>
                <span className="flex gap-1.5">
                  <span className="w-2.5 h-2.5 rounded-full bg-red-500/50"></span>
                  <span className="w-2.5 h-2.5 rounded-full bg-amber-500/50"></span>
                  <span className="w-2.5 h-2.5 rounded-full bg-green-500/50"></span>
                </span>
              </div>
              
              {/* Terminal content window */}
              <div className="p-4 font-mono text-xs text-emerald-400/90 leading-relaxed overflow-y-auto flex-1 h-[360px] space-y-4">
                <div>
                  <p className="text-zinc-500">{"// GuruAI Production Outage Sandbox Console"}</p>
                  <p className="text-zinc-500">{"// Run diagnostic diagnostics to find the failure layer."}</p>
                  <p className="text-[#00E5FF]">System diagnostics loaded. Ready for triage.</p>
                </div>

                {commandsRun.map((run, idx) => (
                  <div key={idx} className="space-y-1">
                    <p className="text-white flex items-center gap-1.5">
                      <span className="text-[#00E5FF]">$</span> {run.command}
                    </p>
                    <pre className="text-zinc-300 font-mono whitespace-pre-wrap bg-white/[0.02] border border-white/5 p-2.5 rounded-lg leading-normal">
                      {run.output}
                    </pre>
                  </div>
                ))}
                <div ref={terminalEndRef} />
              </div>

              {/* Quick Select Command Presets */}
              <div className="px-4 py-2.5 bg-zinc-900 border-t border-white/5 flex flex-wrap gap-1.5">
                <span className="text-[10px] text-zinc-500 font-mono self-center mr-1 uppercase">Presets:</span>
                {catalogTemplate && Object.keys(catalogTemplate.commands).map((cmd) => (
                  <button
                    key={cmd}
                    onClick={() => handleRunCommand(undefined, cmd)}
                    className="rounded bg-white/5 hover:bg-white/10 px-2 py-1 text-[10px] font-mono text-zinc-300 border border-white/5 transition"
                  >
                    {cmd}
                  </button>
                ))}
              </div>

              {/* Command Input Form */}
              <form onSubmit={handleRunCommand} className="flex border-t border-white/5 bg-zinc-900">
                <span className="pl-4 pr-1.5 self-center font-mono text-[#00E5FF] font-semibold text-sm">$</span>
                <input 
                  type="text"
                  value={commandInput}
                  onChange={(e) => setCommandInput(e.target.value)}
                  placeholder="Type troubleshooting command (e.g. ping, nslookup, df -h, kubectl)..."
                  className="flex-1 bg-transparent px-2 py-3 text-xs font-mono text-white placeholder-zinc-600 focus:outline-none"
                />
                <button type="submit" className="px-4 bg-[#00E5FF] hover:bg-[#00B4D8] text-[#050816] font-semibold transition text-xs font-mono flex items-center gap-1">
                  Run <TerminalIcon size={12} />
                </button>
              </form>
            </Card>
          )}

          {/* TAB 2: GLOWING CHARTS TELEMETRY */}
          {activeTab === "telemetry" && (
            <Card className="p-5 border-white/10 bg-black/40 min-h-[480px] space-y-6">
              <div className="flex items-center justify-between">
                <h3 className="font-mono text-xs text-zinc-400 uppercase tracking-widest">Stack Metrics Monitoring</h3>
                <span className="inline-flex items-center gap-1 rounded bg-red-500/10 px-2 py-0.5 text-[10px] font-semibold text-red-400 border border-red-500/20">
                  <Activity size={10} /> Real-time Feed
                </span>
              </div>

              {/* Chart Grid */}
              <div className="grid gap-4 md:grid-cols-2">
                {/* Chart 1: Latency */}
                <div className="rounded-xl border border-white/5 bg-white/[0.01] p-4 space-y-2">
                  <div className="flex justify-between text-xs font-mono text-zinc-400">
                    <span>API Latency</span>
                    <span className="text-red-400 font-semibold">1,240ms</span>
                  </div>
                  <div className="h-24 flex items-end gap-1.5 pt-4">
                    {/* Simulated SVG Graph */}
                    <svg className="w-full h-full" viewBox="0 0 100 40" preserveAspectRatio="none">
                      <path 
                        d="M 0 35 Q 20 34, 40 32 T 60 20 T 80 5 T 100 2" 
                        fill="none" 
                        stroke="#EF4444" 
                        strokeWidth="2.5" 
                      />
                      <path 
                        d="M 0 35 Q 20 34, 40 32 T 60 20 T 80 5 T 100 2 L 100 40 L 0 40 Z" 
                        fill="url(#latencyGrad)" 
                        opacity="0.15"
                      />
                      <defs>
                        <linearGradient id="latencyGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#EF4444" />
                          <stop offset="100%" stopColor="#EF4444" stopOpacity="0" />
                        </linearGradient>
                      </defs>
                    </svg>
                  </div>
                </div>

                {/* Chart 2: CPU Load */}
                <div className="rounded-xl border border-white/5 bg-white/[0.01] p-4 space-y-2">
                  <div className="flex justify-between text-xs font-mono text-zinc-400">
                    <span>Aggregate Node CPU</span>
                    <span className="text-amber-400 font-semibold">91%</span>
                  </div>
                  <div className="h-24 flex items-end gap-1.5 pt-4">
                    <svg className="w-full h-full" viewBox="0 0 100 40" preserveAspectRatio="none">
                      <path 
                        d="M 0 30 Q 15 28, 30 31 T 45 10 T 60 4 T 75 8 T 100 3" 
                        fill="none" 
                        stroke="#F59E0B" 
                        strokeWidth="2.5" 
                      />
                      <path 
                        d="M 0 30 Q 15 28, 30 31 T 45 10 T 60 4 T 75 8 T 100 3 L 100 40 L 0 40 Z" 
                        fill="url(#cpuGrad)" 
                        opacity="0.15"
                      />
                      <defs>
                        <linearGradient id="cpuGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#F59E0B" />
                          <stop offset="100%" stopColor="#F59E0B" stopOpacity="0" />
                        </linearGradient>
                      </defs>
                    </svg>
                  </div>
                </div>

                {/* Chart 3: Error Rate */}
                <div className="rounded-xl border border-white/5 bg-white/[0.01] p-4 space-y-2">
                  <div className="flex justify-between text-xs font-mono text-zinc-400">
                    <span>HTTP 5xx Error Rate</span>
                    <span className="text-red-400 font-semibold">94.2%</span>
                  </div>
                  <div className="h-24 flex items-end gap-1.5 pt-4">
                    <svg className="w-full h-full" viewBox="0 0 100 40" preserveAspectRatio="none">
                      <path 
                        d="M 0 39 Q 20 38, 40 39 T 60 5 T 80 1 T 100 1" 
                        fill="none" 
                        stroke="#EF4444" 
                        strokeWidth="2.5" 
                      />
                      <path 
                        d="M 0 39 Q 20 38, 40 39 T 60 5 T 80 1 T 100 1 L 100 40 L 0 40 Z" 
                        fill="url(#errorGrad)" 
                        opacity="0.15"
                      />
                      <defs>
                        <linearGradient id="errorGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#EF4444" />
                          <stop offset="100%" stopColor="#EF4444" stopOpacity="0" />
                        </linearGradient>
                      </defs>
                    </svg>
                  </div>
                </div>

                {/* Chart 4: Network IO */}
                <div className="rounded-xl border border-white/5 bg-white/[0.01] p-4 space-y-2">
                  <div className="flex justify-between text-xs font-mono text-zinc-400">
                    <span>Egress Bandwidth</span>
                    <span className="text-[#00E5FF] font-semibold">45 MB/s</span>
                  </div>
                  <div className="h-24 flex items-end gap-1.5 pt-4">
                    <svg className="w-full h-full" viewBox="0 0 100 40" preserveAspectRatio="none">
                      <path 
                        d="M 0 20 Q 20 18, 40 22 T 60 35 T 80 38 T 100 37" 
                        fill="none" 
                        stroke="#00E5FF" 
                        strokeWidth="2.5" 
                      />
                      <path 
                        d="M 0 20 Q 20 18, 40 22 T 60 35 T 80 38 T 100 37 L 100 40 L 0 40 Z" 
                        fill="url(#netGrad)" 
                        opacity="0.15"
                      />
                      <defs>
                        <linearGradient id="netGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#00E5FF" />
                          <stop offset="100%" stopColor="#00E5FF" stopOpacity="0" />
                        </linearGradient>
                      </defs>
                    </svg>
                  </div>
                </div>
              </div>

              <div className="rounded-xl border border-dashed border-white/10 bg-white/[0.02] p-4 text-xs font-mono text-zinc-400">
                <p className="font-semibold text-zinc-300 mb-1">Metrics Analysis Logs:</p>
                <p className="text-red-400 animate-pulse">{"// WARNING: Storage IO queue saturation. EBS throttling detected on Database mount."}</p>
                <p className="text-zinc-500 mt-1">{"// Suggestion: Inspect volume configurations using AWS CLI or hypervisor console."}</p>
              </div>
            </Card>
          )}

          {/* TAB 3: DYNAMIC DIAGRAM NODE VISUALIZATION */}
          {activeTab === "diagram" && (
            <Card className="p-5 border-white/10 bg-black/40 min-h-[480px] flex flex-col justify-between">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-mono text-xs text-zinc-400 uppercase tracking-widest font-semibold">Infrastructure Topography</h3>
                <span className="rounded bg-red-500/10 px-2 py-0.5 text-[10px] font-semibold text-red-400 border border-red-500/20">
                  Outage Detected
                </span>
              </div>

              {/* Simulated ASCII/SVG Interactive Topology map */}
              <div className="border border-white/5 rounded-xl bg-black/60 p-6 flex-1 flex flex-col justify-center items-center font-mono text-xs space-y-8 select-none">
                <div className="flex flex-col items-center">
                  <div className="rounded-lg bg-green-500/10 border border-green-500/30 px-3 py-2 text-center text-green-300 font-semibold shadow-[0_0_15px_rgba(34,197,94,0.1)]">
                    [ Cloudflare CDN Edge ]<br />
                    <span className="text-[10px] text-green-400/70">WAF Rule Engine - Active</span>
                  </div>
                </div>
                
                <div className="h-6 w-0.5 bg-zinc-700"></div>

                <div className="flex flex-col items-center">
                  <div className="rounded-lg bg-green-500/10 border border-green-500/30 px-3 py-2 text-center text-green-300 font-semibold shadow-[0_0_15px_rgba(34,197,94,0.1)]">
                    [ Application Load Balancer ]<br />
                    <span className="text-[10px] text-green-400/70">ALB-PROD-01 (gp2)</span>
                  </div>
                </div>

                <div className="flex items-center justify-center gap-12">
                  <div className="flex flex-col items-center">
                    <div className="h-6 w-0.5 bg-zinc-700"></div>
                    <div className="rounded-lg bg-green-500/10 border border-green-500/30 px-3 py-2 text-center text-green-300 font-semibold shadow-[0_0_15px_rgba(34,197,94,0.1)]">
                      [ web-service-nodeA ]<br />
                      <span className="text-[10px] text-green-400/70">CPU: 45%</span>
                    </div>
                  </div>

                  <div className="flex flex-col items-center">
                    <div className="h-6 w-0.5 bg-zinc-700"></div>
                    <div className="rounded-lg bg-red-500/10 border border-red-500/30 px-3 py-2 text-center text-red-400 font-semibold shadow-[0_0_20px_rgba(239,68,68,0.2)] animate-pulse">
                      [ ERROR NODE: {session.domain} ]<br />
                      <span className="text-[10px] text-red-500/70">State: FAILED (503 / Loss)</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-4 text-[11px] text-zinc-500 font-mono text-center">
                Visualizing target layer dependencies. The red node corresponds to the failing domain controller, server node, or route path.
              </div>
            </Card>
          )}
        </div>

        {/* RIGHT COLUMN: AI INCIDENT COMMANDER CHAT & STATUS BROADCASTS */}
        <div className="space-y-6">
          
          {/* AI Commander Chat */}
          <Card className="p-5 border-white/10 bg-black/40 flex flex-col h-[340px]">
            {/* Header / Selector */}
            <div className="border-b border-white/10 pb-3 flex items-center justify-between">
              <div>
                <p className="text-[10px] font-mono text-zinc-500 uppercase tracking-widest">AI Incident Commander</p>
                <h3 className="font-semibold text-white flex items-center gap-1.5 mt-0.5">
                  <User size={14} className="text-[#00E5FF]" /> {activeCommander}
                </h3>
              </div>
              <select 
                value={activeCommander}
                onChange={(e) => setActiveCommander(e.target.value)}
                className="bg-white/5 border border-white/10 rounded px-2 py-1 text-xs text-white font-mono focus:outline-none"
              >
                <option value="CTO" className="bg-[#050816] text-white">CTO (Executive)</option>
                <option value="Manager" className="bg-[#050816] text-white">Manager (Lead)</option>
                <option value="Customer" className="bg-[#050816] text-white">Customer (Client)</option>
                <option value="Security Team" className="bg-[#050816] text-white">Security Team</option>
                <option value="Network Team" className="bg-[#050816] text-white">Network Team</option>
              </select>
            </div>

            {/* Chat Body */}
            <div className="flex-1 overflow-y-auto py-4 space-y-3 pr-1 text-xs">
              {activeChats.map((msg, idx) => (
                <div key={idx} className={`flex flex-col ${msg.sender === "Student" ? "items-end" : "items-start"}`}>
                  <span className="text-[9px] text-zinc-500 font-mono mb-0.5">{msg.sender}</span>
                  <div 
                    className={`rounded-lg px-3 py-2 max-w-[85%] leading-normal ${
                      msg.sender === "Student" 
                        ? "bg-[#00E5FF]/10 border border-[#00E5FF]/20 text-[#00E5FF]" 
                        : "bg-white/[0.03] border border-white/10 text-zinc-200"
                    }`}
                  >
                    {msg.text}
                  </div>
                </div>
              ))}
              <div ref={chatEndRef} />
            </div>

            {/* Chat input */}
            <form onSubmit={handleSendMessage} className="flex gap-2 pt-2 border-t border-white/10">
              <input 
                type="text"
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder={`Ask or update ${activeCommander}...`}
                className="flex-1 bg-white/5 border border-white/10 rounded px-3 py-2 text-xs text-white placeholder-zinc-600 focus:outline-none focus:border-[#00E5FF]/50"
              />
              <button type="submit" className="p-2 bg-[#00E5FF] hover:bg-[#00B4D8] text-[#050816] rounded transition">
                <Send size={14} />
              </button>
            </form>
          </Card>

          {/* Stakeholder Status Broadcast Board */}
          <Card className="p-5 border-white/10 bg-black/40">
            <h2 className="text-sm font-semibold tracking-wider text-zinc-400 uppercase mb-3 flex items-center gap-2">
              <Megaphone size={16} className="text-[#00E5FF]" /> Stakeholder Broadcast Board
            </h2>
            <form onSubmit={handleSendStatusUpdate} className="space-y-3">
              <div>
                <label className="text-[10px] text-zinc-500 font-mono block mb-1">Target Group</label>
                <div className="flex gap-1 bg-white/5 rounded p-0.5 border border-white/5">
                  {["CTO", "Customer", "Internal Teams"].map((t) => (
                    <button
                      key={t}
                      type="button"
                      onClick={() => setCommsTarget(t)}
                      className={`flex-1 text-[10px] font-mono py-1 rounded transition ${
                        commsTarget === t ? "bg-white/10 text-white font-semibold" : "text-zinc-500 hover:text-zinc-300"
                      }`}
                    >
                      {t}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <textarea
                  value={commsText}
                  onChange={(e) => setCommsText(e.target.value)}
                  placeholder="Draft status announcement: 'The team has isolated the S3 CORS rules and is currently redeploying...'"
                  className="w-full bg-white/5 border border-white/10 rounded p-2.5 text-xs text-white placeholder-zinc-600 h-20 focus:outline-none focus:border-[#00E5FF]/50 resize-none"
                />
              </div>

              {commsStatusMessage && (
                <p className="text-[10px] text-green-400 font-mono flex items-center gap-1.5">
                  <CheckCircle size={10} /> {commsStatusMessage}
                </p>
              )}

              <button 
                type="submit"
                disabled={!commsText.trim()}
                className="w-full text-center py-2 bg-white/10 hover:bg-white/20 border border-white/10 hover:border-white/25 rounded text-xs font-mono font-semibold text-white transition disabled:opacity-50"
              >
                Broadcast Communication Update
              </button>
            </form>
          </Card>
        </div>
      </section>

      {/* BOTTOM RESOLUTION AND EVALUATION CONTROL CONSOLE */}
      <section className="mb-12">
        <Card className="p-6 border-red-500/20 bg-black/40">
          <div className="border-b border-white/10 pb-4 mb-6">
            <h2 className="text-lg font-semibold text-white flex items-center gap-2">
              <CheckCircle className="text-[#00FFB3]" size={20} /> Triage Resolution & Outage Remediation Hub
            </h2>
            <p className="text-xs text-zinc-400 mt-1">
              Apply your diagnostic conclusion here. Your answers will be graded by the AI Incident Commander based on root-cause accuracy, resolution validation, communications, and prevention logic.
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-2">
            {/* Step 1: Diagnose */}
            <div className="space-y-4">
              <div>
                <label className="text-xs font-mono font-semibold text-zinc-300 block mb-1.5 uppercase">
                  1. Root Cause Diagnosis Note
                </label>
                <textarea
                  value={rootCauseDiagnosis}
                  onChange={(e) => setRootCauseDiagnosis(e.target.value)}
                  placeholder="Write a clear, detailed explanation of what went wrong, including the specific system layer, trigger mechanism, and proof artifacts gathered (e.g. 'PostgreSQL was blocked because the gp2 EBS volume depleted its IOPS credit balance due to unindexed analytics queries')."
                  className="w-full bg-white/5 border border-white/10 rounded-lg p-3 text-xs text-white placeholder-zinc-500 h-32 focus:outline-none focus:border-[#00E5FF]/50 resize-none font-mono leading-normal"
                />
              </div>

              {/* Step 2: Choose Remediation */}
              <div>
                <label className="text-xs font-mono font-semibold text-zinc-300 block mb-1.5 uppercase">
                  2. Select Active Remediation Action
                </label>
                <select
                  value={selectedRemediationId}
                  onChange={(e) => setSelectedRemediationId(e.target.value)}
                  className="w-full bg-white/5 border border-white/10 rounded-lg px-3 py-2.5 text-xs text-white font-mono focus:outline-none focus:border-[#00E5FF]/50"
                >
                  <option value="" className="bg-[#050816] text-zinc-500">-- Choose Remediation Option --</option>
                  {catalogTemplate?.remediationOptions.map((rem) => (
                    <option key={rem.id} value={rem.id} className="bg-[#050816] text-white">
                      {rem.label}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Step 3: Prevention */}
            <div className="space-y-4">
              <div>
                <label className="text-xs font-mono font-semibold text-zinc-300 block mb-2 uppercase">
                  3. Select Preventive Action Suggestions
                </label>
                <div className="space-y-2 rounded-lg border border-white/10 bg-white/[0.01] p-4 max-h-[190px] overflow-y-auto">
                  {catalogTemplate?.preventiveActionOptions.map((opt, idx) => {
                    // Extract text (remove correct/incorrect suffix for student rendering)
                    const cleanText = opt.split(" (")[0];
                    return (
                      <label key={idx} className="flex items-start gap-2.5 text-xs text-zinc-300 cursor-pointer hover:text-white select-none">
                        <input 
                          type="checkbox"
                          checked={selectedPreventions.includes(opt)}
                          onChange={() => handleTogglePrevention(opt)}
                          className="mt-0.5 rounded border-white/10 bg-white/5 text-[#00E5FF]"
                        />
                        <span>{cleanText}</span>
                      </label>
                    );
                  }) || (
                    <p className="text-xs text-zinc-500 italic font-mono">Select active incident role first.</p>
                  )}
                </div>
              </div>

              {/* Action Submit */}
              <div className="pt-2">
                <button
                  type="button"
                  onClick={handleSubmitEvaluation}
                  disabled={submittingEvaluation || !rootCauseDiagnosis.trim() || !selectedRemediationId}
                  className="w-full py-3.5 bg-gradient-to-r from-[#00E5FF] to-[#00FFB3] hover:from-[#00B4D8] hover:to-[#00E5FF] text-[#050816] font-bold rounded-lg transition text-sm font-mono shadow-[0_0_30px_rgba(0,229,255,0.2)] disabled:opacity-50 flex items-center justify-center gap-2"
                >
                  {submittingEvaluation ? (
                    <>
                      <div className="h-4 w-4 animate-spin rounded-full border-2 border-[#050816] border-t-transparent"></div>
                      Evaluating Remediation Quality...
                    </>
                  ) : (
                    <>
                      Apply Fix & Resolve Outage <CheckCircle size={16} />
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>
        </Card>
      </section>

      {/* DYNAMIC STUDY GUIDE POPUP MODAL */}
      {showStudyModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4">
          <div className="glass max-w-2xl w-full rounded-2xl border border-[#00E5FF]/30 p-6 space-y-6 relative text-left shadow-[0_0_50px_rgba(0,229,255,0.2)] animate-in fade-in zoom-in duration-200">
            <button 
              onClick={() => setShowStudyModal(false)}
              className="absolute top-4 right-4 text-zinc-400 hover:text-white transition cursor-pointer"
            >
              <X size={20} />
            </button>
            
            <div className="flex items-center gap-3 border-b border-white/10 pb-3">
              <BookOpen className="text-[#00FFB3]" size={24} />
              <div>
                <h2 className="text-xl font-bold text-white">
                  {domainStudyGuides[session.domain]?.title || "Outage Study Guide"}
                </h2>
                <p className="text-xs font-mono text-zinc-500 mt-0.5">GuruAI Interactive Knowledge Base</p>
              </div>
            </div>

            <div className="space-y-4 max-h-[420px] overflow-y-auto pr-1 text-xs leading-normal font-sans">
              {/* Hindi Explanation */}
              <div className="rounded-xl bg-[#00FFB3]/5 border border-[#00FFB3]/10 p-4 space-y-1">
                <span className="text-[10px] font-mono text-[#00FFB3] uppercase tracking-wider font-semibold">
                  Study Guide (Hinglish/Hindi)
                </span>
                <p className="text-zinc-200 text-[12px] font-medium leading-relaxed font-sans">
                  {domainStudyGuides[session.domain]?.hindiExplanation}
                </p>
              </div>

              {/* English Explanation */}
              <div className="rounded-xl bg-white/[0.02] border border-white/5 p-4 space-y-1">
                <span className="text-[10px] font-mono text-[#00E5FF] uppercase tracking-wider font-semibold">
                  Concept Breakdown (English)
                </span>
                <p className="text-zinc-300 leading-relaxed">
                  {domainStudyGuides[session.domain]?.englishExplanation}
                </p>
              </div>

              {/* Triage Checklist */}
              <div className="space-y-2">
                <span className="text-[10px] font-mono text-zinc-400 uppercase tracking-wider font-semibold">
                  Step-by-step Triage Checklist
                </span>
                <ul className="space-y-2">
                  {domainStudyGuides[session.domain]?.checklist.map((step, idx) => (
                    <li key={idx} className="flex gap-2.5 items-start bg-white/[0.01] border border-white/5 rounded-lg p-2.5">
                      <span className="font-mono text-[10px] text-[#00FFB3] font-bold">0{idx + 1}.</span>
                      <span className="text-zinc-300 font-mono text-[11px]">{step}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Common Pitfalls */}
              <div className="rounded-xl bg-red-500/5 border border-red-500/10 p-4 space-y-1">
                <span className="text-[10px] font-mono text-red-400 uppercase tracking-wider font-semibold">
                  Common Pitfalls (Kya Galti Karte Hain?)
                </span>
                <p className="text-zinc-300 leading-relaxed">
                  {domainStudyGuides[session.domain]?.pitfalls}
                </p>
              </div>
            </div>

            <div className="border-t border-white/10 pt-4 text-right">
              <button
                onClick={() => setShowStudyModal(false)}
                className="px-4 py-2 bg-[#00E5FF] hover:bg-[#00B4D8] text-[#050816] rounded-lg font-bold font-mono text-xs transition cursor-pointer"
              >
                Understood, Resume Triage
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
